"""settings: app_setting + sector_api_config

Revision ID: 0989cf690bdb
Revises: 388f90002acf
Create Date: 2026-06-06 23:21:07.171506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0989cf690bdb'
down_revision: Union[str, None] = '388f90002acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sector_api_config',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=150), nullable=False),
    sa.Column('api_name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('api_key_secondary_enc', sa.Text(), nullable=True),
    sa.Column('proxy_secret_enc', sa.Text(), nullable=True),
    sa.Column('proxy_url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_test_status', sa.String(length=20), nullable=False),
    sa.Column('last_test_date', sa.String(length=40), nullable=False),
    sa.Column('last_test_detail', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_api_config_provider'), 'sector_api_config', ['provider'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sector_api_config_provider'), table_name='sector_api_config')
    op.drop_table('sector_api_config')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
