"""add trade_intel tables

Revision ID: 14e19953826c
Revises: 1c4cb96934bf
Create Date: 2026-06-06 12:08:57.863224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e19953826c'
down_revision: Union[str, None] = '1c4cb96934bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ti_flows',
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.Enum('export', 'import_', name='tradedirection'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('partner', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ti_flows_period_dir', 'ti_flows', ['period', 'direction'], unique=False)
    op.create_table('ti_scores',
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('hhi_exports', sa.Float(), nullable=True),
    sa.Column('export_diversification', sa.Float(), nullable=True),
    sa.Column('import_dependency', sa.Float(), nullable=True),
    sa.Column('resilience_score', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ti_scores_period', 'ti_scores', ['period'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ti_scores_period', table_name='ti_scores')
    op.drop_table('ti_scores')
    op.drop_index('ix_ti_flows_period_dir', table_name='ti_flows')
    op.drop_table('ti_flows')
    # ### end Alembic commands ###
