"""add macro_monitor tables

Revision ID: 1c4cb96934bf
Revises: 2d738fdbf669
Create Date: 2026-06-06 11:45:08.313920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4cb96934bf'
down_revision: Union[str, None] = '2d738fdbf669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mm_series',
    sa.Column('series_code', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_code', 'period', name='uq_mm_series_period')
    )
    op.create_index('ix_mm_series_code_period', 'mm_series', ['series_code', 'period'], unique=False)
    op.create_table('mm_snapshots',
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('momentum', sa.JSON(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('series_count', sa.Float(), nullable=True),
    sa.Column('signal_count', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', name='uq_mm_snapshot_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mm_snapshots')
    op.drop_index('ix_mm_series_code_period', table_name='mm_series')
    op.drop_table('mm_series')
    # ### end Alembic commands ###
