"""add sector_intel tables

Revision ID: 1ce789e4ec2c
Revises: 14e19953826c
Create Date: 2026-06-06 12:50:24.428210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce789e4ec2c'
down_revision: Union[str, None] = '14e19953826c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('si_scores',
    sa.Column('sector_code', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('iai_score', sa.Float(), nullable=True),
    sa.Column('iai_band', sa.String(length=20), nullable=True),
    sa.Column('sgps_score', sa.Float(), nullable=True),
    sa.Column('iai_breakdown', sa.JSON(), nullable=True),
    sa.Column('sgps_breakdown', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_code', 'period', name='uq_si_sector_period')
    )
    op.create_index('ix_si_scores_sector_period', 'si_scores', ['sector_code', 'period'], unique=False)
    op.create_table('si_sectors',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('si_variables',
    sa.Column('sector_code', sa.String(length=40), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('variable', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_si_var_sector_period', 'si_variables', ['sector_code', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_si_var_sector_period', table_name='si_variables')
    op.drop_table('si_variables')
    op.drop_table('si_sectors')
    op.drop_index('ix_si_scores_sector_period', table_name='si_scores')
    op.drop_table('si_scores')
    # ### end Alembic commands ###
