"""add macro_political_risk tables

Revision ID: 2d738fdbf669
Revises: dc1b15fd8ca1
Create Date: 2026-06-06 11:17:26.606788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d738fdbf669'
down_revision: Union[str, None] = 'dc1b15fd8ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpr_countries',
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('mpr_irmp_snapshots',
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('irmp_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.Enum('bajo', 'moderado', 'elevado', 'alto', name='riskband'), nullable=False),
    sa.Column('peer_set_size', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['mpr_countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'period_end', name='uq_irmp_country_period')
    )
    op.create_index('ix_irmp_country_period', 'mpr_irmp_snapshots', ['country_id', 'period_end'], unique=False)
    op.create_table('mpr_dimension_scores',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['mpr_irmp_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mpr_dimension_scores')
    op.drop_index('ix_irmp_country_period', table_name='mpr_irmp_snapshots')
    op.drop_table('mpr_irmp_snapshots')
    op.drop_table('mpr_countries')
    # ### end Alembic commands ###
