"""add social_dev and esg_climate tables

Revision ID: 388f90002acf
Revises: 1ce789e4ec2c
Create Date: 2026-06-06 13:03:56.730637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388f90002acf'
down_revision: Union[str, None] = '1ce789e4ec2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_indicators',
    sa.Column('theme', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('sector_key', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_esg_ind_theme_period', 'esg_indicators', ['theme', 'period'], unique=False)
    op.create_table('esg_scores',
    sa.Column('sector_key', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('esg_score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=20), nullable=True),
    sa.Column('material', sa.Boolean(), nullable=True),
    sa.Column('materiality_level', sa.String(length=20), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_key', 'period', name='uq_esg_sector_period')
    )
    op.create_index('ix_esg_scores_sector_period', 'esg_scores', ['sector_key', 'period'], unique=False)
    op.create_table('sd_indicators',
    sa.Column('theme', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('disaggregation', sa.String(length=60), nullable=True),
    sa.Column('entity_key', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sd_ind_theme_period', 'sd_indicators', ['theme', 'period'], unique=False)
    op.create_table('sd_scores',
    sa.Column('entity_key', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('development_score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=20), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_key', 'period', name='uq_sd_entity_period')
    )
    op.create_index('ix_sd_scores_entity_period', 'sd_scores', ['entity_key', 'period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sd_scores_entity_period', table_name='sd_scores')
    op.drop_table('sd_scores')
    op.drop_index('ix_sd_ind_theme_period', table_name='sd_indicators')
    op.drop_table('sd_indicators')
    op.drop_index('ix_esg_scores_sector_period', table_name='esg_scores')
    op.drop_table('esg_scores')
    op.drop_index('ix_esg_ind_theme_period', table_name='esg_indicators')
    op.drop_table('esg_indicators')
    # ### end Alembic commands ###
