"""add banking score tables

Revision ID: dc1b15fd8ca1
Revises: 4910ce9ea6ae
Create Date: 2026-03-04 08:39:51.592552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1b15fd8ca1'
down_revision: Union[str, None] = '4910ce9ea6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sib_code', sa.String(length=20), nullable=True),
    sa.Column('bank_type', sa.Enum('banca_multiple', 'aap', 'banco_ahorro_credito', name='banktype'), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('peer_group', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('banking_data',
    sa.Column('bank_id', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('quarterly', 'annual', name='periodtype'), nullable=True),
    sa.Column('patrimonio_tecnico', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('apr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capital_primario', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exposicion_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capital_tier1', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contingentes', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('riesgo_mercado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('provisiones', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cartera_vencida_90d', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('activos_totales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cartera_bruta', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cartera_categoria_a', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cartera_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('suma_top10', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hhi_sectorial_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('castigos', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exposicion_re', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cartera_a_prev', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('utilidad_neta', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('activos_promedio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('patrimonio_promedio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ingresos_financieros', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gastos_financieros', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('activos_productivos_avg', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gastos_operacionales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ingresos_operacionales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('caja_valores', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pasivos_cp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cartera_neta', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('depositos_totales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('activos_liquidos', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pasivos_exigibles', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hhi_ingresos_raw', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('source', sa.Enum('manual', 'sib_api', 'csv_upload', name='datasource'), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'period_end', name='uq_banking_data_bank_period')
    )
    op.create_index('ix_banking_data_bank_period', 'banking_data', ['bank_id', 'period_end'], unique=False)
    op.create_table('rating_results',
    sa.Column('bank_id', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rating_tier', sa.String(length=10), nullable=False),
    sa.Column('solidez_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('calidad_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('eficiencia_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('liquidez_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('diversificacion_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('indicator_details', sa.JSON(), nullable=True),
    sa.Column('model_type', sa.Enum('deterministic', 'ml', name='modeltype'), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'period_end', 'model_type', name='uq_rating_bank_period_model')
    )
    op.create_index('ix_rating_results_bank_period', 'rating_results', ['bank_id', 'period_end'], unique=False)
    op.create_table('reports',
    sa.Column('bank_id', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('report_type', sa.Enum('full_rating', 'scorecard', 'communique', 'datawatch', 'wire', 'criteria', 'sector_outlook', name='reporttype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('narrative_model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('generating', 'completed', 'error', name='reportstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_actions',
    sa.Column('bank_id', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('action_type', sa.Enum('upgrade', 'downgrade', 'confirmacion', 'observacion', name='actiontype'), nullable=False),
    sa.Column('previous_period_end', sa.Date(), nullable=True),
    sa.Column('previous_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('previous_tier', sa.String(length=10), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('new_tier', sa.String(length=10), nullable=False),
    sa.Column('score_delta', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tier_levels_changed', sa.Integer(), nullable=True),
    sa.Column('outlook', sa.Enum('positiva', 'negativa', 'estable', name='outlook'), nullable=True),
    sa.Column('previous_sub_components', sa.JSON(), nullable=True),
    sa.Column('new_sub_components', sa.JSON(), nullable=True),
    sa.Column('communique_report_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['communique_report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating_actions')
    op.drop_table('reports')
    op.drop_index('ix_rating_results_bank_period', table_name='rating_results')
    op.drop_table('rating_results')
    op.drop_index('ix_banking_data_bank_period', table_name='banking_data')
    op.drop_table('banking_data')
    op.drop_table('banks')
    # ### end Alembic commands ###
